// Code generated by protoc-gen-go. DO NOT EDIT.
// source: disk.proto

package imrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiskType int32

const (
	DiskType_filesystem DiskType = 0
	DiskType_block      DiskType = 1
)

var DiskType_name = map[int32]string{
	0: "filesystem",
	1: "block",
}

var DiskType_value = map[string]int32{
	"filesystem": 0,
	"block":      1,
}

func (x DiskType) String() string {
	return proto.EnumName(DiskType_name, int32(x))
}

func (DiskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f96b80c5532b4167, []int{0}
}

type Disk struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	TotalSize            int64    `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	FreeSize             int64    `protobuf:"varint,6,opt,name=free_size,json=freeSize,proto3" json:"free_size,omitempty"`
	TotalBlocks          int64    `protobuf:"varint,7,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	FreeBlocks           int64    `protobuf:"varint,8,opt,name=free_blocks,json=freeBlocks,proto3" json:"free_blocks,omitempty"`
	BlockSize            int64    `protobuf:"varint,9,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	ClusterSize          int64    `protobuf:"varint,10,opt,name=cluster_size,json=clusterSize,proto3" json:"cluster_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disk) Reset()         { *m = Disk{} }
func (m *Disk) String() string { return proto.CompactTextString(m) }
func (*Disk) ProtoMessage()    {}
func (*Disk) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96b80c5532b4167, []int{0}
}

func (m *Disk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disk.Unmarshal(m, b)
}
func (m *Disk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disk.Marshal(b, m, deterministic)
}
func (m *Disk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disk.Merge(m, src)
}
func (m *Disk) XXX_Size() int {
	return xxx_messageInfo_Disk.Size(m)
}
func (m *Disk) XXX_DiscardUnknown() {
	xxx_messageInfo_Disk.DiscardUnknown(m)
}

var xxx_messageInfo_Disk proto.InternalMessageInfo

func (m *Disk) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Disk) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Disk) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Disk) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Disk) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *Disk) GetFreeSize() int64 {
	if m != nil {
		return m.FreeSize
	}
	return 0
}

func (m *Disk) GetTotalBlocks() int64 {
	if m != nil {
		return m.TotalBlocks
	}
	return 0
}

func (m *Disk) GetFreeBlocks() int64 {
	if m != nil {
		return m.FreeBlocks
	}
	return 0
}

func (m *Disk) GetBlockSize() int64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *Disk) GetClusterSize() int64 {
	if m != nil {
		return m.ClusterSize
	}
	return 0
}

type ReplicaInstance struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SpecSize             uint64   `protobuf:"varint,2,opt,name=spec_size,json=specSize,proto3" json:"spec_size,omitempty"`
	ActualSize           uint64   `protobuf:"varint,3,opt,name=actual_size,json=actualSize,proto3" json:"actual_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaInstance) Reset()         { *m = ReplicaInstance{} }
func (m *ReplicaInstance) String() string { return proto.CompactTextString(m) }
func (*ReplicaInstance) ProtoMessage()    {}
func (*ReplicaInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96b80c5532b4167, []int{1}
}

func (m *ReplicaInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaInstance.Unmarshal(m, b)
}
func (m *ReplicaInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaInstance.Marshal(b, m, deterministic)
}
func (m *ReplicaInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaInstance.Merge(m, src)
}
func (m *ReplicaInstance) XXX_Size() int {
	return xxx_messageInfo_ReplicaInstance.Size(m)
}
func (m *ReplicaInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaInstance.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaInstance proto.InternalMessageInfo

func (m *ReplicaInstance) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ReplicaInstance) GetSpecSize() uint64 {
	if m != nil {
		return m.SpecSize
	}
	return 0
}

func (m *ReplicaInstance) GetActualSize() uint64 {
	if m != nil {
		return m.ActualSize
	}
	return 0
}

type DiskCreateRequest struct {
	DiskType             DiskType `protobuf:"varint,1,opt,name=disk_type,json=diskType,proto3,enum=imrpc.DiskType" json:"disk_type,omitempty"`
	DiskName             string   `protobuf:"bytes,2,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	DiskPath             string   `protobuf:"bytes,3,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	BlockSize            int64    `protobuf:"varint,4,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskCreateRequest) Reset()         { *m = DiskCreateRequest{} }
func (m *DiskCreateRequest) String() string { return proto.CompactTextString(m) }
func (*DiskCreateRequest) ProtoMessage()    {}
func (*DiskCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96b80c5532b4167, []int{2}
}

func (m *DiskCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskCreateRequest.Unmarshal(m, b)
}
func (m *DiskCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskCreateRequest.Marshal(b, m, deterministic)
}
func (m *DiskCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskCreateRequest.Merge(m, src)
}
func (m *DiskCreateRequest) XXX_Size() int {
	return xxx_messageInfo_DiskCreateRequest.Size(m)
}
func (m *DiskCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskCreateRequest proto.InternalMessageInfo

func (m *DiskCreateRequest) GetDiskType() DiskType {
	if m != nil {
		return m.DiskType
	}
	return DiskType_filesystem
}

func (m *DiskCreateRequest) GetDiskName() string {
	if m != nil {
		return m.DiskName
	}
	return ""
}

func (m *DiskCreateRequest) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

func (m *DiskCreateRequest) GetBlockSize() int64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

type DiskGetRequest struct {
	DiskType             DiskType `protobuf:"varint,1,opt,name=disk_type,json=diskType,proto3,enum=imrpc.DiskType" json:"disk_type,omitempty"`
	DiskName             string   `protobuf:"bytes,2,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	DiskPath             string   `protobuf:"bytes,3,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskGetRequest) Reset()         { *m = DiskGetRequest{} }
func (m *DiskGetRequest) String() string { return proto.CompactTextString(m) }
func (*DiskGetRequest) ProtoMessage()    {}
func (*DiskGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96b80c5532b4167, []int{3}
}

func (m *DiskGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskGetRequest.Unmarshal(m, b)
}
func (m *DiskGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskGetRequest.Marshal(b, m, deterministic)
}
func (m *DiskGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskGetRequest.Merge(m, src)
}
func (m *DiskGetRequest) XXX_Size() int {
	return xxx_messageInfo_DiskGetRequest.Size(m)
}
func (m *DiskGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskGetRequest proto.InternalMessageInfo

func (m *DiskGetRequest) GetDiskType() DiskType {
	if m != nil {
		return m.DiskType
	}
	return DiskType_filesystem
}

func (m *DiskGetRequest) GetDiskName() string {
	if m != nil {
		return m.DiskName
	}
	return ""
}

func (m *DiskGetRequest) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

type DiskDeleteRequest struct {
	DiskName             string   `protobuf:"bytes,1,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	DiskUuid             string   `protobuf:"bytes,2,opt,name=disk_uuid,json=diskUuid,proto3" json:"disk_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskDeleteRequest) Reset()         { *m = DiskDeleteRequest{} }
func (m *DiskDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DiskDeleteRequest) ProtoMessage()    {}
func (*DiskDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96b80c5532b4167, []int{4}
}

func (m *DiskDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskDeleteRequest.Unmarshal(m, b)
}
func (m *DiskDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskDeleteRequest.Marshal(b, m, deterministic)
}
func (m *DiskDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskDeleteRequest.Merge(m, src)
}
func (m *DiskDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DiskDeleteRequest.Size(m)
}
func (m *DiskDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskDeleteRequest proto.InternalMessageInfo

func (m *DiskDeleteRequest) GetDiskName() string {
	if m != nil {
		return m.DiskName
	}
	return ""
}

func (m *DiskDeleteRequest) GetDiskUuid() string {
	if m != nil {
		return m.DiskUuid
	}
	return ""
}

type DiskReplicaInstanceListRequest struct {
	DiskType             DiskType `protobuf:"varint,1,opt,name=disk_type,json=diskType,proto3,enum=imrpc.DiskType" json:"disk_type,omitempty"`
	DiskName             string   `protobuf:"bytes,2,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskReplicaInstanceListRequest) Reset()         { *m = DiskReplicaInstanceListRequest{} }
func (m *DiskReplicaInstanceListRequest) String() string { return proto.CompactTextString(m) }
func (*DiskReplicaInstanceListRequest) ProtoMessage()    {}
func (*DiskReplicaInstanceListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96b80c5532b4167, []int{5}
}

func (m *DiskReplicaInstanceListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskReplicaInstanceListRequest.Unmarshal(m, b)
}
func (m *DiskReplicaInstanceListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskReplicaInstanceListRequest.Marshal(b, m, deterministic)
}
func (m *DiskReplicaInstanceListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskReplicaInstanceListRequest.Merge(m, src)
}
func (m *DiskReplicaInstanceListRequest) XXX_Size() int {
	return xxx_messageInfo_DiskReplicaInstanceListRequest.Size(m)
}
func (m *DiskReplicaInstanceListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskReplicaInstanceListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskReplicaInstanceListRequest proto.InternalMessageInfo

func (m *DiskReplicaInstanceListRequest) GetDiskType() DiskType {
	if m != nil {
		return m.DiskType
	}
	return DiskType_filesystem
}

func (m *DiskReplicaInstanceListRequest) GetDiskName() string {
	if m != nil {
		return m.DiskName
	}
	return ""
}

type DiskReplicaInstanceListResponse struct {
	ReplicaInstances     map[string]*ReplicaInstance `protobuf:"bytes,1,rep,name=replica_instances,json=replicaInstances,proto3" json:"replica_instances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DiskReplicaInstanceListResponse) Reset()         { *m = DiskReplicaInstanceListResponse{} }
func (m *DiskReplicaInstanceListResponse) String() string { return proto.CompactTextString(m) }
func (*DiskReplicaInstanceListResponse) ProtoMessage()    {}
func (*DiskReplicaInstanceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96b80c5532b4167, []int{6}
}

func (m *DiskReplicaInstanceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskReplicaInstanceListResponse.Unmarshal(m, b)
}
func (m *DiskReplicaInstanceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskReplicaInstanceListResponse.Marshal(b, m, deterministic)
}
func (m *DiskReplicaInstanceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskReplicaInstanceListResponse.Merge(m, src)
}
func (m *DiskReplicaInstanceListResponse) XXX_Size() int {
	return xxx_messageInfo_DiskReplicaInstanceListResponse.Size(m)
}
func (m *DiskReplicaInstanceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskReplicaInstanceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiskReplicaInstanceListResponse proto.InternalMessageInfo

func (m *DiskReplicaInstanceListResponse) GetReplicaInstances() map[string]*ReplicaInstance {
	if m != nil {
		return m.ReplicaInstances
	}
	return nil
}

type DiskReplicaInstanceDeleteRequest struct {
	DiskType             DiskType `protobuf:"varint,1,opt,name=disk_type,json=diskType,proto3,enum=imrpc.DiskType" json:"disk_type,omitempty"`
	DiskName             string   `protobuf:"bytes,2,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	DiskUuid             string   `protobuf:"bytes,3,opt,name=disk_uuid,json=diskUuid,proto3" json:"disk_uuid,omitempty"`
	ReplciaInstanceName  string   `protobuf:"bytes,4,opt,name=replcia_instance_name,json=replciaInstanceName,proto3" json:"replcia_instance_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskReplicaInstanceDeleteRequest) Reset()         { *m = DiskReplicaInstanceDeleteRequest{} }
func (m *DiskReplicaInstanceDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DiskReplicaInstanceDeleteRequest) ProtoMessage()    {}
func (*DiskReplicaInstanceDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96b80c5532b4167, []int{7}
}

func (m *DiskReplicaInstanceDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskReplicaInstanceDeleteRequest.Unmarshal(m, b)
}
func (m *DiskReplicaInstanceDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskReplicaInstanceDeleteRequest.Marshal(b, m, deterministic)
}
func (m *DiskReplicaInstanceDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskReplicaInstanceDeleteRequest.Merge(m, src)
}
func (m *DiskReplicaInstanceDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DiskReplicaInstanceDeleteRequest.Size(m)
}
func (m *DiskReplicaInstanceDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskReplicaInstanceDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskReplicaInstanceDeleteRequest proto.InternalMessageInfo

func (m *DiskReplicaInstanceDeleteRequest) GetDiskType() DiskType {
	if m != nil {
		return m.DiskType
	}
	return DiskType_filesystem
}

func (m *DiskReplicaInstanceDeleteRequest) GetDiskName() string {
	if m != nil {
		return m.DiskName
	}
	return ""
}

func (m *DiskReplicaInstanceDeleteRequest) GetDiskUuid() string {
	if m != nil {
		return m.DiskUuid
	}
	return ""
}

func (m *DiskReplicaInstanceDeleteRequest) GetReplciaInstanceName() string {
	if m != nil {
		return m.ReplciaInstanceName
	}
	return ""
}

func init() {
	proto.RegisterEnum("imrpc.DiskType", DiskType_name, DiskType_value)
	proto.RegisterType((*Disk)(nil), "imrpc.Disk")
	proto.RegisterType((*ReplicaInstance)(nil), "imrpc.ReplicaInstance")
	proto.RegisterType((*DiskCreateRequest)(nil), "imrpc.DiskCreateRequest")
	proto.RegisterType((*DiskGetRequest)(nil), "imrpc.DiskGetRequest")
	proto.RegisterType((*DiskDeleteRequest)(nil), "imrpc.DiskDeleteRequest")
	proto.RegisterType((*DiskReplicaInstanceListRequest)(nil), "imrpc.DiskReplicaInstanceListRequest")
	proto.RegisterType((*DiskReplicaInstanceListResponse)(nil), "imrpc.DiskReplicaInstanceListResponse")
	proto.RegisterMapType((map[string]*ReplicaInstance)(nil), "imrpc.DiskReplicaInstanceListResponse.ReplicaInstancesEntry")
	proto.RegisterType((*DiskReplicaInstanceDeleteRequest)(nil), "imrpc.DiskReplicaInstanceDeleteRequest")
}

func init() { proto.RegisterFile("disk.proto", fileDescriptor_f96b80c5532b4167) }

var fileDescriptor_f96b80c5532b4167 = []byte{
	// 674 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xbe, 0x8e, 0x93, 0x36, 0x3e, 0xbe, 0x4a, 0xd3, 0xb9, 0x6a, 0xaf, 0x6f, 0xaa, 0xde, 0x06,
	0x4b, 0x85, 0x0a, 0x15, 0x57, 0x4a, 0x37, 0x08, 0x55, 0x2c, 0xa0, 0x15, 0x42, 0x02, 0x84, 0x5c,
	0x60, 0x03, 0x52, 0xe5, 0x3a, 0xa7, 0xed, 0x28, 0xfe, 0xc3, 0x33, 0xae, 0x48, 0x9f, 0x83, 0x15,
	0x2f, 0xc2, 0x8e, 0xf7, 0xe1, 0x2d, 0xd0, 0x9c, 0xb1, 0x89, 0x1d, 0x35, 0xd0, 0x4d, 0xd9, 0x8d,
	0xbf, 0xef, 0x9b, 0xf3, 0xf3, 0x9d, 0x33, 0x06, 0x18, 0x73, 0x31, 0xf1, 0xb2, 0x3c, 0x95, 0x29,
	0xeb, 0xf0, 0x38, 0xcf, 0xc2, 0xc1, 0xc6, 0x79, 0x9a, 0x9e, 0x47, 0xb8, 0x47, 0xe0, 0x69, 0x71,
	0xb6, 0x87, 0x71, 0x26, 0xa7, 0x5a, 0x33, 0xe8, 0xf1, 0x38, 0x4c, 0xe3, 0x38, 0x4d, 0xf4, 0xb7,
	0xfb, 0xb9, 0x05, 0xed, 0x43, 0x2e, 0x26, 0xac, 0x07, 0x2d, 0x3e, 0x76, 0x8c, 0xa1, 0xb1, 0x63,
	0xf9, 0x2d, 0x3e, 0x66, 0x0c, 0xda, 0x45, 0xc1, 0xc7, 0x4e, 0x8b, 0x10, 0x3a, 0x2b, 0x2c, 0x0b,
	0xe4, 0x85, 0x63, 0x6a, 0x4c, 0x9d, 0x15, 0x26, 0xa7, 0x19, 0x3a, 0x6d, 0x8d, 0xa9, 0x33, 0xdb,
	0x04, 0x90, 0xa9, 0x0c, 0xa2, 0x13, 0xc1, 0xaf, 0xd0, 0xe9, 0x0c, 0x8d, 0x1d, 0xd3, 0xb7, 0x08,
	0x39, 0xe6, 0x57, 0xc8, 0x36, 0xc0, 0x3a, 0xcb, 0x11, 0x35, 0xbb, 0x44, 0x6c, 0x57, 0x01, 0x44,
	0xde, 0x81, 0xbf, 0xf5, 0xdd, 0xd3, 0x28, 0x0d, 0x27, 0xc2, 0x59, 0x26, 0xde, 0x26, 0xec, 0x09,
	0x41, 0x6c, 0x0b, 0x6c, 0xba, 0x5f, 0x2a, 0xba, 0xa4, 0x00, 0x05, 0x95, 0x82, 0x4d, 0x00, 0xe2,
	0x74, 0x06, 0x4b, 0xe7, 0x27, 0xa4, 0x4a, 0x11, 0x46, 0x85, 0x90, 0x98, 0x6b, 0x01, 0xe8, 0x14,
	0x25, 0xa6, 0x24, 0x6e, 0x08, 0x2b, 0x3e, 0x66, 0x11, 0x0f, 0x83, 0xe7, 0x89, 0x90, 0x41, 0x12,
	0xe2, 0x4f, 0x43, 0x8c, 0x9a, 0x21, 0x1b, 0x60, 0x89, 0x0c, 0x43, 0x1d, 0x46, 0x39, 0xd5, 0xf6,
	0xbb, 0x0a, 0xa0, 0x34, 0x5b, 0x60, 0x07, 0xa1, 0x2c, 0x2a, 0x1b, 0x4c, 0xa2, 0x41, 0x43, 0x94,
	0xe4, 0x8b, 0x01, 0xab, 0xca, 0xfb, 0xa7, 0x39, 0x06, 0x12, 0x7d, 0xfc, 0x58, 0xa0, 0x90, 0x6c,
	0x17, 0x2c, 0x35, 0xd3, 0x13, 0x72, 0x55, 0x25, 0xeb, 0x8d, 0x56, 0x3c, 0x9a, 0xac, 0xa7, 0xc4,
	0x6f, 0xa6, 0x19, 0xfa, 0xdd, 0x71, 0x79, 0x52, 0x15, 0x90, 0x3a, 0x09, 0x62, 0x2c, 0x67, 0x45,
	0xe4, 0xab, 0x20, 0x9e, 0x91, 0xb5, 0xa1, 0x11, 0xf9, 0x5a, 0x0d, 0xae, 0x69, 0x52, 0x7b, 0xce,
	0x24, 0xf7, 0x13, 0xf4, 0x54, 0xba, 0x67, 0x28, 0xff, 0x70, 0x61, 0xee, 0x4b, 0xed, 0xca, 0x21,
	0x46, 0x38, 0x73, 0xa5, 0x11, 0xce, 0x58, 0x10, 0xae, 0xb6, 0xb0, 0x44, 0xbe, 0x2d, 0xf8, 0xd8,
	0x9d, 0xc0, 0xff, 0x2a, 0xdc, 0xdc, 0x38, 0x5f, 0x70, 0x71, 0x0b, 0x8d, 0xb9, 0xdf, 0x0d, 0xd8,
	0x5a, 0x98, 0x4d, 0x64, 0x69, 0x22, 0x90, 0x71, 0x58, 0xcd, 0x35, 0x7d, 0xc2, 0x4b, 0x5e, 0x38,
	0xc6, 0xd0, 0xdc, 0xb1, 0x47, 0x07, 0xb5, 0xb4, 0xbf, 0x08, 0xe1, 0xcd, 0x71, 0xe2, 0x28, 0x91,
	0xf9, 0xd4, 0xef, 0xe7, 0x73, 0xf0, 0xe0, 0x3d, 0xac, 0x5d, 0x2b, 0x65, 0x7d, 0x30, 0x27, 0x38,
	0x2d, 0x8d, 0x54, 0x47, 0xb6, 0x0b, 0x9d, 0xcb, 0x20, 0x2a, 0x74, 0x4b, 0xf6, 0x68, 0xbd, 0xac,
	0x64, 0xee, 0xba, 0xaf, 0x45, 0x8f, 0x5a, 0x0f, 0x0d, 0xf7, 0x9b, 0x01, 0xc3, 0x6b, 0x0a, 0x6d,
	0xce, 0xed, 0x16, 0x96, 0x86, 0xa6, 0x6c, 0x36, 0xa7, 0xcc, 0x46, 0xb0, 0xa6, 0xba, 0x0f, 0xf9,
	0xcc, 0x54, 0x1d, 0x45, 0xff, 0x97, 0xfe, 0x29, 0xc9, 0xaa, 0x48, 0x15, 0xf0, 0xfe, 0x36, 0x74,
	0xab, 0x1a, 0x58, 0x0f, 0xe0, 0x8c, 0x47, 0x28, 0xa6, 0x42, 0x62, 0xdc, 0xff, 0x8b, 0x59, 0xd0,
	0xa1, 0xb7, 0xd0, 0x37, 0x46, 0x5f, 0x4d, 0xb0, 0x95, 0xee, 0x18, 0xf3, 0x4b, 0x1e, 0x22, 0xdb,
	0x07, 0x98, 0xbd, 0x5a, 0xe6, 0xd4, 0xba, 0x69, 0x3c, 0xe4, 0x81, 0x5d, 0x63, 0xd8, 0x63, 0x7d,
	0x49, 0x9b, 0xd3, 0xb8, 0xd4, 0xf0, 0x6b, 0xb0, 0xee, 0xe9, 0xbf, 0xb7, 0x57, 0xfd, 0xbd, 0xbd,
	0x23, 0xf5, 0xf7, 0x66, 0x0f, 0x60, 0xb9, 0x7c, 0x8e, 0x6c, 0xad, 0x76, 0x79, 0xf6, 0x3c, 0x9b,
	0xe9, 0x2e, 0xe0, 0xdf, 0x05, 0x3b, 0xc4, 0xb6, 0x7f, 0xb7, 0x63, 0x3a, 0xdc, 0xdd, 0x9b, 0xad,
	0x22, 0xfb, 0x00, 0xff, 0x2d, 0x5c, 0x02, 0x76, 0x6f, 0x71, 0x90, 0x9b, 0xb5, 0x7d, 0x00, 0xf0,
	0x0e, 0x73, 0xc1, 0xd3, 0x44, 0x75, 0xbe, 0x40, 0x35, 0xa8, 0x96, 0xb5, 0x94, 0x56, 0xb5, 0x9d,
	0x2e, 0x91, 0x6e, 0xff, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0xb5, 0xe4, 0x2a, 0x25, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiskServiceClient is the client API for DiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiskServiceClient interface {
	DiskCreate(ctx context.Context, in *DiskCreateRequest, opts ...grpc.CallOption) (*Disk, error)
	DiskDelete(ctx context.Context, in *DiskDeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DiskGet(ctx context.Context, in *DiskGetRequest, opts ...grpc.CallOption) (*Disk, error)
	DiskReplicaInstanceList(ctx context.Context, in *DiskReplicaInstanceListRequest, opts ...grpc.CallOption) (*DiskReplicaInstanceListResponse, error)
	DiskReplicaInstanceDelete(ctx context.Context, in *DiskReplicaInstanceDeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	VersionGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type diskServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiskServiceClient(cc *grpc.ClientConn) DiskServiceClient {
	return &diskServiceClient{cc}
}

func (c *diskServiceClient) DiskCreate(ctx context.Context, in *DiskCreateRequest, opts ...grpc.CallOption) (*Disk, error) {
	out := new(Disk)
	err := c.cc.Invoke(ctx, "/imrpc.DiskService/DiskCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskServiceClient) DiskDelete(ctx context.Context, in *DiskDeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/imrpc.DiskService/DiskDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskServiceClient) DiskGet(ctx context.Context, in *DiskGetRequest, opts ...grpc.CallOption) (*Disk, error) {
	out := new(Disk)
	err := c.cc.Invoke(ctx, "/imrpc.DiskService/DiskGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskServiceClient) DiskReplicaInstanceList(ctx context.Context, in *DiskReplicaInstanceListRequest, opts ...grpc.CallOption) (*DiskReplicaInstanceListResponse, error) {
	out := new(DiskReplicaInstanceListResponse)
	err := c.cc.Invoke(ctx, "/imrpc.DiskService/DiskReplicaInstanceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskServiceClient) DiskReplicaInstanceDelete(ctx context.Context, in *DiskReplicaInstanceDeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/imrpc.DiskService/DiskReplicaInstanceDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskServiceClient) VersionGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/imrpc.DiskService/VersionGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiskServiceServer is the server API for DiskService service.
type DiskServiceServer interface {
	DiskCreate(context.Context, *DiskCreateRequest) (*Disk, error)
	DiskDelete(context.Context, *DiskDeleteRequest) (*empty.Empty, error)
	DiskGet(context.Context, *DiskGetRequest) (*Disk, error)
	DiskReplicaInstanceList(context.Context, *DiskReplicaInstanceListRequest) (*DiskReplicaInstanceListResponse, error)
	DiskReplicaInstanceDelete(context.Context, *DiskReplicaInstanceDeleteRequest) (*empty.Empty, error)
	VersionGet(context.Context, *empty.Empty) (*VersionResponse, error)
}

// UnimplementedDiskServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiskServiceServer struct {
}

func (*UnimplementedDiskServiceServer) DiskCreate(ctx context.Context, req *DiskCreateRequest) (*Disk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskCreate not implemented")
}
func (*UnimplementedDiskServiceServer) DiskDelete(ctx context.Context, req *DiskDeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskDelete not implemented")
}
func (*UnimplementedDiskServiceServer) DiskGet(ctx context.Context, req *DiskGetRequest) (*Disk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskGet not implemented")
}
func (*UnimplementedDiskServiceServer) DiskReplicaInstanceList(ctx context.Context, req *DiskReplicaInstanceListRequest) (*DiskReplicaInstanceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskReplicaInstanceList not implemented")
}
func (*UnimplementedDiskServiceServer) DiskReplicaInstanceDelete(ctx context.Context, req *DiskReplicaInstanceDeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskReplicaInstanceDelete not implemented")
}
func (*UnimplementedDiskServiceServer) VersionGet(ctx context.Context, req *empty.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VersionGet not implemented")
}

func RegisterDiskServiceServer(s *grpc.Server, srv DiskServiceServer) {
	s.RegisterService(&_DiskService_serviceDesc, srv)
}

func _DiskService_DiskCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServiceServer).DiskCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.DiskService/DiskCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServiceServer).DiskCreate(ctx, req.(*DiskCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiskService_DiskDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServiceServer).DiskDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.DiskService/DiskDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServiceServer).DiskDelete(ctx, req.(*DiskDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiskService_DiskGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServiceServer).DiskGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.DiskService/DiskGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServiceServer).DiskGet(ctx, req.(*DiskGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiskService_DiskReplicaInstanceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskReplicaInstanceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServiceServer).DiskReplicaInstanceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.DiskService/DiskReplicaInstanceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServiceServer).DiskReplicaInstanceList(ctx, req.(*DiskReplicaInstanceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiskService_DiskReplicaInstanceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskReplicaInstanceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServiceServer).DiskReplicaInstanceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.DiskService/DiskReplicaInstanceDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServiceServer).DiskReplicaInstanceDelete(ctx, req.(*DiskReplicaInstanceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiskService_VersionGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServiceServer).VersionGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.DiskService/VersionGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServiceServer).VersionGet(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imrpc.DiskService",
	HandlerType: (*DiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiskCreate",
			Handler:    _DiskService_DiskCreate_Handler,
		},
		{
			MethodName: "DiskDelete",
			Handler:    _DiskService_DiskDelete_Handler,
		},
		{
			MethodName: "DiskGet",
			Handler:    _DiskService_DiskGet_Handler,
		},
		{
			MethodName: "DiskReplicaInstanceList",
			Handler:    _DiskService_DiskReplicaInstanceList_Handler,
		},
		{
			MethodName: "DiskReplicaInstanceDelete",
			Handler:    _DiskService_DiskReplicaInstanceDelete_Handler,
		},
		{
			MethodName: "VersionGet",
			Handler:    _DiskService_VersionGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disk.proto",
}
