// Code generated by protoc-gen-go. DO NOT EDIT.
// source: instance.proto

package imrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Process struct {
	Binary               string   `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{0}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetBinary() string {
	if m != nil {
		return m.Binary
	}
	return ""
}

func (m *Process) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type InstanceSpec struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	BackendStoreDriver   string   `protobuf:"bytes,3,opt,name=backend_store_driver,json=backendStoreDriver,proto3" json:"backend_store_driver,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	DiskUuid             string   `protobuf:"bytes,5,opt,name=disk_uuid,json=diskUuid,proto3" json:"disk_uuid,omitempty"`
	PortCount            int32    `protobuf:"varint,6,opt,name=port_count,json=portCount,proto3" json:"port_count,omitempty"`
	PortArgs             []string `protobuf:"bytes,7,rep,name=port_args,json=portArgs,proto3" json:"port_args,omitempty"`
	Process              *Process `protobuf:"bytes,8,opt,name=process,proto3" json:"process,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceSpec) Reset()         { *m = InstanceSpec{} }
func (m *InstanceSpec) String() string { return proto.CompactTextString(m) }
func (*InstanceSpec) ProtoMessage()    {}
func (*InstanceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{1}
}

func (m *InstanceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceSpec.Unmarshal(m, b)
}
func (m *InstanceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceSpec.Marshal(b, m, deterministic)
}
func (m *InstanceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceSpec.Merge(m, src)
}
func (m *InstanceSpec) XXX_Size() int {
	return xxx_messageInfo_InstanceSpec.Size(m)
}
func (m *InstanceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceSpec proto.InternalMessageInfo

func (m *InstanceSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstanceSpec) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *InstanceSpec) GetBackendStoreDriver() string {
	if m != nil {
		return m.BackendStoreDriver
	}
	return ""
}

func (m *InstanceSpec) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InstanceSpec) GetDiskUuid() string {
	if m != nil {
		return m.DiskUuid
	}
	return ""
}

func (m *InstanceSpec) GetPortCount() int32 {
	if m != nil {
		return m.PortCount
	}
	return 0
}

func (m *InstanceSpec) GetPortArgs() []string {
	if m != nil {
		return m.PortArgs
	}
	return nil
}

func (m *InstanceSpec) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

type InstanceStatus struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	PortStart            int32    `protobuf:"varint,3,opt,name=port_start,json=portStart,proto3" json:"port_start,omitempty"`
	PortEnd              int32    `protobuf:"varint,4,opt,name=port_end,json=portEnd,proto3" json:"port_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceStatus) Reset()         { *m = InstanceStatus{} }
func (m *InstanceStatus) String() string { return proto.CompactTextString(m) }
func (*InstanceStatus) ProtoMessage()    {}
func (*InstanceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{2}
}

func (m *InstanceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceStatus.Unmarshal(m, b)
}
func (m *InstanceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceStatus.Marshal(b, m, deterministic)
}
func (m *InstanceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceStatus.Merge(m, src)
}
func (m *InstanceStatus) XXX_Size() int {
	return xxx_messageInfo_InstanceStatus.Size(m)
}
func (m *InstanceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceStatus proto.InternalMessageInfo

func (m *InstanceStatus) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *InstanceStatus) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *InstanceStatus) GetPortStart() int32 {
	if m != nil {
		return m.PortStart
	}
	return 0
}

func (m *InstanceStatus) GetPortEnd() int32 {
	if m != nil {
		return m.PortEnd
	}
	return 0
}

type InstanceCreateRequest struct {
	Spec                 *InstanceSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InstanceCreateRequest) Reset()         { *m = InstanceCreateRequest{} }
func (m *InstanceCreateRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceCreateRequest) ProtoMessage()    {}
func (*InstanceCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{3}
}

func (m *InstanceCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceCreateRequest.Unmarshal(m, b)
}
func (m *InstanceCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceCreateRequest.Marshal(b, m, deterministic)
}
func (m *InstanceCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceCreateRequest.Merge(m, src)
}
func (m *InstanceCreateRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceCreateRequest.Size(m)
}
func (m *InstanceCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceCreateRequest proto.InternalMessageInfo

func (m *InstanceCreateRequest) GetSpec() *InstanceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type InstanceDeleteRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceDeleteRequest) Reset()         { *m = InstanceDeleteRequest{} }
func (m *InstanceDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceDeleteRequest) ProtoMessage()    {}
func (*InstanceDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{4}
}

func (m *InstanceDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceDeleteRequest.Unmarshal(m, b)
}
func (m *InstanceDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceDeleteRequest.Marshal(b, m, deterministic)
}
func (m *InstanceDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceDeleteRequest.Merge(m, src)
}
func (m *InstanceDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceDeleteRequest.Size(m)
}
func (m *InstanceDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceDeleteRequest proto.InternalMessageInfo

func (m *InstanceDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InstanceGetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceGetRequest) Reset()         { *m = InstanceGetRequest{} }
func (m *InstanceGetRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceGetRequest) ProtoMessage()    {}
func (*InstanceGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{5}
}

func (m *InstanceGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGetRequest.Unmarshal(m, b)
}
func (m *InstanceGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGetRequest.Marshal(b, m, deterministic)
}
func (m *InstanceGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGetRequest.Merge(m, src)
}
func (m *InstanceGetRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceGetRequest.Size(m)
}
func (m *InstanceGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGetRequest proto.InternalMessageInfo

func (m *InstanceGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InstanceResponse struct {
	Spec                 *InstanceSpec   `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *InstanceStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Deleted              bool            `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InstanceResponse) Reset()         { *m = InstanceResponse{} }
func (m *InstanceResponse) String() string { return proto.CompactTextString(m) }
func (*InstanceResponse) ProtoMessage()    {}
func (*InstanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{6}
}

func (m *InstanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceResponse.Unmarshal(m, b)
}
func (m *InstanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceResponse.Marshal(b, m, deterministic)
}
func (m *InstanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceResponse.Merge(m, src)
}
func (m *InstanceResponse) XXX_Size() int {
	return xxx_messageInfo_InstanceResponse.Size(m)
}
func (m *InstanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceResponse proto.InternalMessageInfo

func (m *InstanceResponse) GetSpec() *InstanceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *InstanceResponse) GetStatus() *InstanceStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InstanceResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type InstanceListResponse struct {
	Instances            map[string]*InstanceResponse `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *InstanceListResponse) Reset()         { *m = InstanceListResponse{} }
func (m *InstanceListResponse) String() string { return proto.CompactTextString(m) }
func (*InstanceListResponse) ProtoMessage()    {}
func (*InstanceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{7}
}

func (m *InstanceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceListResponse.Unmarshal(m, b)
}
func (m *InstanceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceListResponse.Marshal(b, m, deterministic)
}
func (m *InstanceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceListResponse.Merge(m, src)
}
func (m *InstanceListResponse) XXX_Size() int {
	return xxx_messageInfo_InstanceListResponse.Size(m)
}
func (m *InstanceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceListResponse proto.InternalMessageInfo

func (m *InstanceListResponse) GetInstances() map[string]*InstanceResponse {
	if m != nil {
		return m.Instances
	}
	return nil
}

type InstanceLogRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceLogRequest) Reset()         { *m = InstanceLogRequest{} }
func (m *InstanceLogRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceLogRequest) ProtoMessage()    {}
func (*InstanceLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{8}
}

func (m *InstanceLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceLogRequest.Unmarshal(m, b)
}
func (m *InstanceLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceLogRequest.Marshal(b, m, deterministic)
}
func (m *InstanceLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceLogRequest.Merge(m, src)
}
func (m *InstanceLogRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceLogRequest.Size(m)
}
func (m *InstanceLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceLogRequest proto.InternalMessageInfo

func (m *InstanceLogRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InstanceLogResponse struct {
	Line                 string   `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceLogResponse) Reset()         { *m = InstanceLogResponse{} }
func (m *InstanceLogResponse) String() string { return proto.CompactTextString(m) }
func (*InstanceLogResponse) ProtoMessage()    {}
func (*InstanceLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{9}
}

func (m *InstanceLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceLogResponse.Unmarshal(m, b)
}
func (m *InstanceLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceLogResponse.Marshal(b, m, deterministic)
}
func (m *InstanceLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceLogResponse.Merge(m, src)
}
func (m *InstanceLogResponse) XXX_Size() int {
	return xxx_messageInfo_InstanceLogResponse.Size(m)
}
func (m *InstanceLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceLogResponse proto.InternalMessageInfo

func (m *InstanceLogResponse) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

type InstanceReplaceRequest struct {
	Spec                 *InstanceSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	TerminateSignal      string        `protobuf:"bytes,2,opt,name=terminate_signal,json=terminateSignal,proto3" json:"terminate_signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InstanceReplaceRequest) Reset()         { *m = InstanceReplaceRequest{} }
func (m *InstanceReplaceRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceReplaceRequest) ProtoMessage()    {}
func (*InstanceReplaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{10}
}

func (m *InstanceReplaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceReplaceRequest.Unmarshal(m, b)
}
func (m *InstanceReplaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceReplaceRequest.Marshal(b, m, deterministic)
}
func (m *InstanceReplaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceReplaceRequest.Merge(m, src)
}
func (m *InstanceReplaceRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceReplaceRequest.Size(m)
}
func (m *InstanceReplaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceReplaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceReplaceRequest proto.InternalMessageInfo

func (m *InstanceReplaceRequest) GetSpec() *InstanceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *InstanceReplaceRequest) GetTerminateSignal() string {
	if m != nil {
		return m.TerminateSignal
	}
	return ""
}

type InstanceVersionResponse struct {
	Version                           string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GitCommit                         string   `protobuf:"bytes,2,opt,name=gitCommit,proto3" json:"gitCommit,omitempty"`
	BuildDate                         string   `protobuf:"bytes,3,opt,name=buildDate,proto3" json:"buildDate,omitempty"`
	InstanceManagerAPIVersion         int64    `protobuf:"varint,4,opt,name=instanceManagerAPIVersion,proto3" json:"instanceManagerAPIVersion,omitempty"`
	InstanceManagerAPIMinVersion      int64    `protobuf:"varint,5,opt,name=instanceManagerAPIMinVersion,proto3" json:"instanceManagerAPIMinVersion,omitempty"`
	InstanceManagerProxyAPIVersion    int64    `protobuf:"varint,6,opt,name=instanceManagerProxyAPIVersion,proto3" json:"instanceManagerProxyAPIVersion,omitempty"`
	InstanceManagerProxyAPIMinVersion int64    `protobuf:"varint,7,opt,name=instanceManagerProxyAPIMinVersion,proto3" json:"instanceManagerProxyAPIMinVersion,omitempty"`
	XXX_NoUnkeyedLiteral              struct{} `json:"-"`
	XXX_unrecognized                  []byte   `json:"-"`
	XXX_sizecache                     int32    `json:"-"`
}

func (m *InstanceVersionResponse) Reset()         { *m = InstanceVersionResponse{} }
func (m *InstanceVersionResponse) String() string { return proto.CompactTextString(m) }
func (*InstanceVersionResponse) ProtoMessage()    {}
func (*InstanceVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{11}
}

func (m *InstanceVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceVersionResponse.Unmarshal(m, b)
}
func (m *InstanceVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceVersionResponse.Marshal(b, m, deterministic)
}
func (m *InstanceVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceVersionResponse.Merge(m, src)
}
func (m *InstanceVersionResponse) XXX_Size() int {
	return xxx_messageInfo_InstanceVersionResponse.Size(m)
}
func (m *InstanceVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceVersionResponse proto.InternalMessageInfo

func (m *InstanceVersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InstanceVersionResponse) GetGitCommit() string {
	if m != nil {
		return m.GitCommit
	}
	return ""
}

func (m *InstanceVersionResponse) GetBuildDate() string {
	if m != nil {
		return m.BuildDate
	}
	return ""
}

func (m *InstanceVersionResponse) GetInstanceManagerAPIVersion() int64 {
	if m != nil {
		return m.InstanceManagerAPIVersion
	}
	return 0
}

func (m *InstanceVersionResponse) GetInstanceManagerAPIMinVersion() int64 {
	if m != nil {
		return m.InstanceManagerAPIMinVersion
	}
	return 0
}

func (m *InstanceVersionResponse) GetInstanceManagerProxyAPIVersion() int64 {
	if m != nil {
		return m.InstanceManagerProxyAPIVersion
	}
	return 0
}

func (m *InstanceVersionResponse) GetInstanceManagerProxyAPIMinVersion() int64 {
	if m != nil {
		return m.InstanceManagerProxyAPIMinVersion
	}
	return 0
}

func init() {
	proto.RegisterType((*Process)(nil), "imrpc.Process")
	proto.RegisterType((*InstanceSpec)(nil), "imrpc.InstanceSpec")
	proto.RegisterType((*InstanceStatus)(nil), "imrpc.InstanceStatus")
	proto.RegisterType((*InstanceCreateRequest)(nil), "imrpc.InstanceCreateRequest")
	proto.RegisterType((*InstanceDeleteRequest)(nil), "imrpc.InstanceDeleteRequest")
	proto.RegisterType((*InstanceGetRequest)(nil), "imrpc.InstanceGetRequest")
	proto.RegisterType((*InstanceResponse)(nil), "imrpc.InstanceResponse")
	proto.RegisterType((*InstanceListResponse)(nil), "imrpc.InstanceListResponse")
	proto.RegisterMapType((map[string]*InstanceResponse)(nil), "imrpc.InstanceListResponse.InstancesEntry")
	proto.RegisterType((*InstanceLogRequest)(nil), "imrpc.InstanceLogRequest")
	proto.RegisterType((*InstanceLogResponse)(nil), "imrpc.InstanceLogResponse")
	proto.RegisterType((*InstanceReplaceRequest)(nil), "imrpc.InstanceReplaceRequest")
	proto.RegisterType((*InstanceVersionResponse)(nil), "imrpc.InstanceVersionResponse")
}

func init() { proto.RegisterFile("instance.proto", fileDescriptor_fd22322185b2070b) }

var fileDescriptor_fd22322185b2070b = []byte{
	// 836 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5d, 0x6f, 0x23, 0x35,
	0x14, 0xdd, 0x69, 0xbe, 0x6f, 0xa0, 0x5b, 0xdd, 0xed, 0x76, 0xa7, 0x69, 0x77, 0x15, 0xe6, 0x85,
	0x2c, 0x68, 0xb3, 0x55, 0x10, 0x12, 0x42, 0x3c, 0xb0, 0x34, 0x85, 0xad, 0x68, 0xa5, 0x6a, 0xaa,
	0x85, 0xc7, 0xc8, 0x99, 0x31, 0x83, 0xd5, 0xc4, 0x33, 0xd8, 0x9e, 0x8a, 0x20, 0xf1, 0x86, 0xc4,
	0x4f, 0xe2, 0x9f, 0xf0, 0x77, 0x40, 0xf6, 0xd8, 0x99, 0xe9, 0x74, 0x93, 0xc2, 0x9b, 0x7d, 0xee,
	0xf1, 0xb9, 0xc7, 0xd7, 0xbe, 0x36, 0xec, 0x32, 0x2e, 0x15, 0xe1, 0x11, 0x1d, 0x67, 0x22, 0x55,
	0x29, 0xb6, 0xd8, 0x52, 0x64, 0xd1, 0xe0, 0x28, 0x49, 0xd3, 0x64, 0x41, 0x5f, 0x1b, 0x70, 0x9e,
	0xff, 0xf4, 0x9a, 0x2e, 0x33, 0xb5, 0x2a, 0x38, 0xc1, 0xe7, 0xd0, 0xb9, 0x12, 0x69, 0x44, 0xa5,
	0xc4, 0x03, 0x68, 0xcf, 0x19, 0x27, 0x62, 0xe5, 0x7b, 0x43, 0x6f, 0xd4, 0x0b, 0xed, 0x0c, 0x11,
	0x9a, 0x44, 0x24, 0xd2, 0xdf, 0x19, 0x36, 0x46, 0xbd, 0xd0, 0x8c, 0x83, 0x7f, 0x3c, 0xf8, 0xe0,
	0xdc, 0x66, 0xbb, 0xce, 0x68, 0xa4, 0x49, 0x9c, 0x2c, 0xa9, 0x5d, 0x6a, 0xc6, 0x1a, 0x53, 0xab,
	0x8c, 0xfa, 0x3b, 0x05, 0xa6, 0xc7, 0x78, 0x02, 0xfb, 0x73, 0x12, 0xdd, 0x50, 0x1e, 0xcf, 0xa4,
	0x4a, 0x05, 0x9d, 0xc5, 0x82, 0xdd, 0x52, 0xe1, 0x37, 0x0c, 0x07, 0x6d, 0xec, 0x5a, 0x87, 0xa6,
	0x26, 0xa2, 0x55, 0x24, 0xfb, 0x8d, 0xfa, 0xcd, 0xa1, 0x37, 0x6a, 0x84, 0x66, 0x8c, 0x47, 0xd0,
	0x8b, 0x99, 0xbc, 0x99, 0xe5, 0x39, 0x8b, 0xfd, 0x96, 0x59, 0xda, 0xd5, 0xc0, 0xbb, 0x9c, 0xc5,
	0xf8, 0x1c, 0x20, 0x4b, 0x85, 0x9a, 0x45, 0x69, 0xce, 0x95, 0xdf, 0x1e, 0x7a, 0xa3, 0x56, 0xd8,
	0xd3, 0xc8, 0xa9, 0x06, 0xf4, 0x5a, 0x13, 0x36, 0x7b, 0xea, 0x98, 0x3d, 0x75, 0x35, 0xf0, 0x46,
	0x24, 0x12, 0x47, 0xd0, 0xc9, 0x8a, 0x72, 0xf8, 0xdd, 0xa1, 0x37, 0xea, 0x4f, 0x76, 0xc7, 0xa6,
	0x88, 0x63, 0x5b, 0xa4, 0xd0, 0x85, 0x83, 0xdf, 0x61, 0x77, 0x5d, 0x00, 0x45, 0x54, 0x2e, 0x71,
	0x1f, 0x5a, 0x52, 0x11, 0xe5, 0x6a, 0x50, 0x4c, 0x74, 0x3a, 0x2a, 0x44, 0x2a, 0x66, 0x4b, 0x99,
	0xd8, 0x4a, 0x74, 0x0d, 0x70, 0x29, 0x93, 0xb5, 0x55, 0xa9, 0x88, 0x50, 0xa6, 0x06, 0xd6, 0xea,
	0xb5, 0x06, 0xf0, 0x10, 0x8c, 0xb3, 0x19, 0xe5, 0xb1, 0xd9, 0x7e, 0x2b, 0xec, 0xe8, 0xf9, 0x19,
	0x8f, 0x83, 0xaf, 0xe1, 0xa9, 0x4b, 0x7f, 0x2a, 0x28, 0x51, 0x34, 0xa4, 0xbf, 0xe4, 0x54, 0x2a,
	0xfc, 0x18, 0x9a, 0x32, 0xa3, 0x91, 0x31, 0xd1, 0x9f, 0x3c, 0xb1, 0xf6, 0xab, 0x67, 0x15, 0x1a,
	0x42, 0xf0, 0x69, 0xa9, 0x30, 0xa5, 0x0b, 0x5a, 0x2a, 0xbc, 0xe7, 0x28, 0x83, 0x11, 0xa0, 0x23,
	0x7f, 0x47, 0xd5, 0x36, 0xe6, 0x1f, 0x1e, 0xec, 0x39, 0x6a, 0x48, 0x65, 0x96, 0x72, 0x49, 0xff,
	0xb3, 0x29, 0x7c, 0x05, 0x6d, 0x69, 0xaa, 0x69, 0x4a, 0xd5, 0x9f, 0x3c, 0xad, 0x53, 0x4d, 0x30,
	0xb4, 0x24, 0xf4, 0xa1, 0x13, 0x1b, 0xef, 0xb1, 0x29, 0x5e, 0x37, 0x74, 0xd3, 0xe0, 0x2f, 0x0f,
	0xf6, 0xdd, 0xa2, 0x0b, 0x26, 0xd5, 0xda, 0xca, 0x5b, 0xe8, 0xb9, 0x36, 0x91, 0xbe, 0x37, 0x6c,
	0x8c, 0xfa, 0x93, 0x4f, 0x6a, 0x49, 0xaa, 0xfc, 0x35, 0x28, 0xcf, 0xb8, 0x12, 0xab, 0xb0, 0x5c,
	0x3c, 0x78, 0x57, 0xde, 0x80, 0x22, 0x88, 0x7b, 0xd0, 0xb8, 0xa1, 0xae, 0x7d, 0xf4, 0x10, 0x5f,
	0x41, 0xeb, 0x96, 0x2c, 0x72, 0x6a, 0xb7, 0xf3, 0xac, 0x96, 0xc9, 0x65, 0x09, 0x0b, 0xd6, 0x97,
	0x3b, 0x5f, 0x78, 0xd5, 0x52, 0x5f, 0xa4, 0xc9, 0xb6, 0x52, 0xbf, 0x84, 0x27, 0x77, 0x98, 0x76,
	0x87, 0x08, 0xcd, 0x05, 0xe3, 0xeb, 0xb6, 0xd3, 0xe3, 0x60, 0x01, 0x07, 0x65, 0xce, 0x6c, 0x41,
	0xa2, 0xff, 0x7d, 0x5f, 0xf0, 0x25, 0xec, 0x29, 0x2a, 0x96, 0x8c, 0x13, 0x45, 0x67, 0x92, 0x25,
	0x9c, 0x2c, 0x6c, 0x8a, 0xc7, 0x6b, 0xfc, 0xda, 0xc0, 0xc1, 0x9f, 0x0d, 0x78, 0xe6, 0x14, 0x7e,
	0xa0, 0x42, 0xb2, 0x94, 0xaf, 0xdd, 0xf9, 0xd0, 0xb9, 0x2d, 0x20, 0xbb, 0x17, 0x37, 0xc5, 0x63,
	0xe8, 0x25, 0x4c, 0x9d, 0xa6, 0xcb, 0x25, 0x53, 0x56, 0xb9, 0x04, 0x74, 0x74, 0x9e, 0xb3, 0x45,
	0x3c, 0xd5, 0x1d, 0x56, 0xbc, 0x16, 0x25, 0x80, 0x5f, 0xc1, 0xa1, 0x3b, 0x98, 0x4b, 0xc2, 0x49,
	0x42, 0xc5, 0x9b, 0xab, 0x73, 0x9b, 0xda, 0xbe, 0x1c, 0x9b, 0x09, 0xf8, 0x0d, 0x1c, 0xdf, 0x0f,
	0x5e, 0x32, 0xee, 0x04, 0x5a, 0x46, 0x60, 0x2b, 0x07, 0xbf, 0x85, 0x17, 0xb5, 0xf8, 0x95, 0x48,
	0x7f, 0x5d, 0x55, 0x6c, 0xb4, 0x8d, 0xca, 0x03, 0x2c, 0xbc, 0x80, 0x8f, 0x36, 0x30, 0x2a, 0x86,
	0x3a, 0x46, 0xea, 0x61, 0xe2, 0xe4, 0xef, 0x26, 0x3c, 0x5e, 0x9f, 0x25, 0x15, 0xb7, 0x2c, 0xa2,
	0x78, 0x5e, 0xde, 0xdb, 0xe2, 0xe9, 0xc0, 0xe3, 0xda, 0xa9, 0xdf, 0x79, 0x51, 0x06, 0x9b, 0x2e,
	0x6d, 0xf0, 0xa8, 0x2a, 0x55, 0xbc, 0x21, 0xf7, 0xa4, 0xee, 0x3c, 0x2d, 0xdb, 0xa4, 0x4e, 0xa1,
	0x5f, 0x79, 0x61, 0xf0, 0xb0, 0xc6, 0x2c, 0x5f, 0x9d, 0x6d, 0x22, 0x67, 0xe5, 0xaf, 0xa4, 0x9b,
	0x18, 0x0f, 0xc6, 0xc5, 0xdf, 0x37, 0x76, 0x7f, 0xdf, 0xf8, 0x4c, 0xff, 0x7d, 0x83, 0xa3, 0x2d,
	0x1d, 0x1f, 0x3c, 0xc2, 0xb7, 0xa5, 0x97, 0x8b, 0x34, 0xb9, 0xe7, 0xa5, 0x6c, 0xcb, 0xc1, 0xe0,
	0x7d, 0x21, 0xa7, 0x73, 0xe2, 0xe1, 0x14, 0x3e, 0x74, 0xa1, 0x1f, 0x89, 0x8a, 0x7e, 0xde, 0xe8,
	0x68, 0xf3, 0xa6, 0x4e, 0x3c, 0xfc, 0xbe, 0x3c, 0x44, 0xdb, 0xbd, 0xf8, 0xfc, 0x1e, 0xbf, 0xda,
	0xd5, 0xdb, 0x6a, 0x34, 0x05, 0xb0, 0xb7, 0x43, 0xd7, 0x79, 0x93, 0x9f, 0x17, 0x35, 0x81, 0x5a,
	0x1b, 0xcf, 0xdb, 0x86, 0xff, 0xd9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xd6, 0xe8, 0x57,
	0x74, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InstanceServiceClient is the client API for InstanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InstanceServiceClient interface {
	InstanceCreate(ctx context.Context, in *InstanceCreateRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	InstanceDelete(ctx context.Context, in *InstanceDeleteRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	InstanceGet(ctx context.Context, in *InstanceGetRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	InstanceList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InstanceListResponse, error)
	InstanceLog(ctx context.Context, in *InstanceLogRequest, opts ...grpc.CallOption) (InstanceService_InstanceLogClient, error)
	InstanceWatch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (InstanceService_InstanceWatchClient, error)
	InstanceReplace(ctx context.Context, in *InstanceReplaceRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	VersionGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InstanceVersionResponse, error)
}

type instanceServiceClient struct {
	cc *grpc.ClientConn
}

func NewInstanceServiceClient(cc *grpc.ClientConn) InstanceServiceClient {
	return &instanceServiceClient{cc}
}

func (c *instanceServiceClient) InstanceCreate(ctx context.Context, in *InstanceCreateRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, "/imrpc.InstanceService/InstanceCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceServiceClient) InstanceDelete(ctx context.Context, in *InstanceDeleteRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, "/imrpc.InstanceService/InstanceDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceServiceClient) InstanceGet(ctx context.Context, in *InstanceGetRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, "/imrpc.InstanceService/InstanceGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceServiceClient) InstanceList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InstanceListResponse, error) {
	out := new(InstanceListResponse)
	err := c.cc.Invoke(ctx, "/imrpc.InstanceService/InstanceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceServiceClient) InstanceLog(ctx context.Context, in *InstanceLogRequest, opts ...grpc.CallOption) (InstanceService_InstanceLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InstanceService_serviceDesc.Streams[0], "/imrpc.InstanceService/InstanceLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &instanceServiceInstanceLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InstanceService_InstanceLogClient interface {
	Recv() (*InstanceLogResponse, error)
	grpc.ClientStream
}

type instanceServiceInstanceLogClient struct {
	grpc.ClientStream
}

func (x *instanceServiceInstanceLogClient) Recv() (*InstanceLogResponse, error) {
	m := new(InstanceLogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *instanceServiceClient) InstanceWatch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (InstanceService_InstanceWatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InstanceService_serviceDesc.Streams[1], "/imrpc.InstanceService/InstanceWatch", opts...)
	if err != nil {
		return nil, err
	}
	x := &instanceServiceInstanceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InstanceService_InstanceWatchClient interface {
	Recv() (*InstanceResponse, error)
	grpc.ClientStream
}

type instanceServiceInstanceWatchClient struct {
	grpc.ClientStream
}

func (x *instanceServiceInstanceWatchClient) Recv() (*InstanceResponse, error) {
	m := new(InstanceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *instanceServiceClient) InstanceReplace(ctx context.Context, in *InstanceReplaceRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, "/imrpc.InstanceService/InstanceReplace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceServiceClient) VersionGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InstanceVersionResponse, error) {
	out := new(InstanceVersionResponse)
	err := c.cc.Invoke(ctx, "/imrpc.InstanceService/VersionGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstanceServiceServer is the server API for InstanceService service.
type InstanceServiceServer interface {
	InstanceCreate(context.Context, *InstanceCreateRequest) (*InstanceResponse, error)
	InstanceDelete(context.Context, *InstanceDeleteRequest) (*InstanceResponse, error)
	InstanceGet(context.Context, *InstanceGetRequest) (*InstanceResponse, error)
	InstanceList(context.Context, *empty.Empty) (*InstanceListResponse, error)
	InstanceLog(*InstanceLogRequest, InstanceService_InstanceLogServer) error
	InstanceWatch(*empty.Empty, InstanceService_InstanceWatchServer) error
	InstanceReplace(context.Context, *InstanceReplaceRequest) (*InstanceResponse, error)
	VersionGet(context.Context, *empty.Empty) (*InstanceVersionResponse, error)
}

// UnimplementedInstanceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInstanceServiceServer struct {
}

func (*UnimplementedInstanceServiceServer) InstanceCreate(ctx context.Context, req *InstanceCreateRequest) (*InstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstanceCreate not implemented")
}
func (*UnimplementedInstanceServiceServer) InstanceDelete(ctx context.Context, req *InstanceDeleteRequest) (*InstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstanceDelete not implemented")
}
func (*UnimplementedInstanceServiceServer) InstanceGet(ctx context.Context, req *InstanceGetRequest) (*InstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstanceGet not implemented")
}
func (*UnimplementedInstanceServiceServer) InstanceList(ctx context.Context, req *empty.Empty) (*InstanceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstanceList not implemented")
}
func (*UnimplementedInstanceServiceServer) InstanceLog(req *InstanceLogRequest, srv InstanceService_InstanceLogServer) error {
	return status.Errorf(codes.Unimplemented, "method InstanceLog not implemented")
}
func (*UnimplementedInstanceServiceServer) InstanceWatch(req *empty.Empty, srv InstanceService_InstanceWatchServer) error {
	return status.Errorf(codes.Unimplemented, "method InstanceWatch not implemented")
}
func (*UnimplementedInstanceServiceServer) InstanceReplace(ctx context.Context, req *InstanceReplaceRequest) (*InstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstanceReplace not implemented")
}
func (*UnimplementedInstanceServiceServer) VersionGet(ctx context.Context, req *empty.Empty) (*InstanceVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VersionGet not implemented")
}

func RegisterInstanceServiceServer(s *grpc.Server, srv InstanceServiceServer) {
	s.RegisterService(&_InstanceService_serviceDesc, srv)
}

func _InstanceService_InstanceCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).InstanceCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.InstanceService/InstanceCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).InstanceCreate(ctx, req.(*InstanceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceService_InstanceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).InstanceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.InstanceService/InstanceDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).InstanceDelete(ctx, req.(*InstanceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceService_InstanceGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).InstanceGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.InstanceService/InstanceGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).InstanceGet(ctx, req.(*InstanceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceService_InstanceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).InstanceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.InstanceService/InstanceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).InstanceList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceService_InstanceLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstanceLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstanceServiceServer).InstanceLog(m, &instanceServiceInstanceLogServer{stream})
}

type InstanceService_InstanceLogServer interface {
	Send(*InstanceLogResponse) error
	grpc.ServerStream
}

type instanceServiceInstanceLogServer struct {
	grpc.ServerStream
}

func (x *instanceServiceInstanceLogServer) Send(m *InstanceLogResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _InstanceService_InstanceWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstanceServiceServer).InstanceWatch(m, &instanceServiceInstanceWatchServer{stream})
}

type InstanceService_InstanceWatchServer interface {
	Send(*InstanceResponse) error
	grpc.ServerStream
}

type instanceServiceInstanceWatchServer struct {
	grpc.ServerStream
}

func (x *instanceServiceInstanceWatchServer) Send(m *InstanceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _InstanceService_InstanceReplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).InstanceReplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.InstanceService/InstanceReplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).InstanceReplace(ctx, req.(*InstanceReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceService_VersionGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).VersionGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imrpc.InstanceService/VersionGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).VersionGet(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _InstanceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imrpc.InstanceService",
	HandlerType: (*InstanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstanceCreate",
			Handler:    _InstanceService_InstanceCreate_Handler,
		},
		{
			MethodName: "InstanceDelete",
			Handler:    _InstanceService_InstanceDelete_Handler,
		},
		{
			MethodName: "InstanceGet",
			Handler:    _InstanceService_InstanceGet_Handler,
		},
		{
			MethodName: "InstanceList",
			Handler:    _InstanceService_InstanceList_Handler,
		},
		{
			MethodName: "InstanceReplace",
			Handler:    _InstanceService_InstanceReplace_Handler,
		},
		{
			MethodName: "VersionGet",
			Handler:    _InstanceService_VersionGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InstanceLog",
			Handler:       _InstanceService_InstanceLog_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstanceWatch",
			Handler:       _InstanceService_InstanceWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "instance.proto",
}
