# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import disk_pb2 as disk__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DiskServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DiskCreate = channel.unary_unary(
        '/imrpc.DiskService/DiskCreate',
        request_serializer=disk__pb2.DiskCreateRequest.SerializeToString,
        response_deserializer=disk__pb2.DiskCreateResponse.FromString,
        )
    self.DiskInfo = channel.unary_unary(
        '/imrpc.DiskService/DiskInfo',
        request_serializer=disk__pb2.DiskInfoRequest.SerializeToString,
        response_deserializer=disk__pb2.DiskInfoResponse.FromString,
        )
    self.ReplicaCreate = channel.unary_unary(
        '/imrpc.DiskService/ReplicaCreate',
        request_serializer=disk__pb2.ReplicaCreateRequest.SerializeToString,
        response_deserializer=disk__pb2.ReplicaCreateResponse.FromString,
        )
    self.ReplicaDelete = channel.unary_unary(
        '/imrpc.DiskService/ReplicaDelete',
        request_serializer=disk__pb2.ReplicaDeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ReplicaList = channel.unary_unary(
        '/imrpc.DiskService/ReplicaList',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=disk__pb2.ReplicaListResponse.FromString,
        )
    self.ReplicaInfo = channel.unary_unary(
        '/imrpc.DiskService/ReplicaInfo',
        request_serializer=disk__pb2.ReplicaInfoRequest.SerializeToString,
        response_deserializer=disk__pb2.ReplicaInfoResponse.FromString,
        )


class DiskServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DiskCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DiskInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiskServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DiskCreate': grpc.unary_unary_rpc_method_handler(
          servicer.DiskCreate,
          request_deserializer=disk__pb2.DiskCreateRequest.FromString,
          response_serializer=disk__pb2.DiskCreateResponse.SerializeToString,
      ),
      'DiskInfo': grpc.unary_unary_rpc_method_handler(
          servicer.DiskInfo,
          request_deserializer=disk__pb2.DiskInfoRequest.FromString,
          response_serializer=disk__pb2.DiskInfoResponse.SerializeToString,
      ),
      'ReplicaCreate': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaCreate,
          request_deserializer=disk__pb2.ReplicaCreateRequest.FromString,
          response_serializer=disk__pb2.ReplicaCreateResponse.SerializeToString,
      ),
      'ReplicaDelete': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaDelete,
          request_deserializer=disk__pb2.ReplicaDeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ReplicaList': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaList,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=disk__pb2.ReplicaListResponse.SerializeToString,
      ),
      'ReplicaInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaInfo,
          request_deserializer=disk__pb2.ReplicaInfoRequest.FromString,
          response_serializer=disk__pb2.ReplicaInfoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'imrpc.DiskService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
