# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: disk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import imcommon_pb2 as imcommon__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='disk.proto',
  package='imrpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndisk.proto\x12\x05imrpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0eimcommon.proto\"\xb8\x01\n\x04\x44isk\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x12\n\ntotal_size\x18\x05 \x01(\x03\x12\x11\n\tfree_size\x18\x06 \x01(\x03\x12\x14\n\x0ctotal_blocks\x18\x07 \x01(\x03\x12\x13\n\x0b\x66ree_blocks\x18\x08 \x01(\x03\x12\x12\n\nblock_size\x18\t \x01(\x03\x12\x14\n\x0c\x63luster_size\x18\n \x01(\x03\"q\n\x11\x44iskCreateRequest\x12\"\n\tdisk_type\x18\x01 \x01(\x0e\x32\x0f.imrpc.DiskType\x12\x11\n\tdisk_name\x18\x02 \x01(\t\x12\x11\n\tdisk_path\x18\x03 \x01(\t\x12\x12\n\nblock_size\x18\x04 \x01(\x03\"Z\n\x0e\x44iskGetRequest\x12\"\n\tdisk_type\x18\x01 \x01(\x0e\x32\x0f.imrpc.DiskType\x12\x11\n\tdisk_name\x18\x02 \x01(\t\x12\x11\n\tdisk_path\x18\x03 \x01(\t\"9\n\x11\x44iskDeleteRequest\x12\x11\n\tdisk_name\x18\x01 \x01(\t\x12\x11\n\tdisk_uuid\x18\x02 \x01(\t*%\n\x08\x44iskType\x12\x0e\n\nfilesystem\x10\x00\x12\t\n\x05\x62lock\x10\x01\x32\xef\x01\n\x0b\x44iskService\x12\x33\n\nDiskCreate\x12\x18.imrpc.DiskCreateRequest\x1a\x0b.imrpc.Disk\x12>\n\nDiskDelete\x12\x18.imrpc.DiskDeleteRequest\x1a\x16.google.protobuf.Empty\x12-\n\x07\x44iskGet\x12\x15.imrpc.DiskGetRequest\x1a\x0b.imrpc.Disk\x12<\n\nVersionGet\x12\x16.google.protobuf.Empty\x1a\x16.imrpc.VersionResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,imcommon__pb2.DESCRIPTOR,])

_DISKTYPE = _descriptor.EnumDescriptor(
  name='DiskType',
  full_name='imrpc.DiskType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='filesystem', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='block', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=519,
  serialized_end=556,
)
_sym_db.RegisterEnumDescriptor(_DISKTYPE)

DiskType = enum_type_wrapper.EnumTypeWrapper(_DISKTYPE)
filesystem = 0
block = 1



_DISK = _descriptor.Descriptor(
  name='Disk',
  full_name='imrpc.Disk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='imrpc.Disk.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='imrpc.Disk.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='imrpc.Disk.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='imrpc.Disk.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_size', full_name='imrpc.Disk.total_size', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_size', full_name='imrpc.Disk.free_size', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_blocks', full_name='imrpc.Disk.total_blocks', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_blocks', full_name='imrpc.Disk.free_blocks', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_size', full_name='imrpc.Disk.block_size', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cluster_size', full_name='imrpc.Disk.cluster_size', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=251,
)


_DISKCREATEREQUEST = _descriptor.Descriptor(
  name='DiskCreateRequest',
  full_name='imrpc.DiskCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='disk_type', full_name='imrpc.DiskCreateRequest.disk_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_name', full_name='imrpc.DiskCreateRequest.disk_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_path', full_name='imrpc.DiskCreateRequest.disk_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_size', full_name='imrpc.DiskCreateRequest.block_size', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=366,
)


_DISKGETREQUEST = _descriptor.Descriptor(
  name='DiskGetRequest',
  full_name='imrpc.DiskGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='disk_type', full_name='imrpc.DiskGetRequest.disk_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_name', full_name='imrpc.DiskGetRequest.disk_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_path', full_name='imrpc.DiskGetRequest.disk_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=458,
)


_DISKDELETEREQUEST = _descriptor.Descriptor(
  name='DiskDeleteRequest',
  full_name='imrpc.DiskDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='disk_name', full_name='imrpc.DiskDeleteRequest.disk_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_uuid', full_name='imrpc.DiskDeleteRequest.disk_uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=517,
)

_DISKCREATEREQUEST.fields_by_name['disk_type'].enum_type = _DISKTYPE
_DISKGETREQUEST.fields_by_name['disk_type'].enum_type = _DISKTYPE
DESCRIPTOR.message_types_by_name['Disk'] = _DISK
DESCRIPTOR.message_types_by_name['DiskCreateRequest'] = _DISKCREATEREQUEST
DESCRIPTOR.message_types_by_name['DiskGetRequest'] = _DISKGETREQUEST
DESCRIPTOR.message_types_by_name['DiskDeleteRequest'] = _DISKDELETEREQUEST
DESCRIPTOR.enum_types_by_name['DiskType'] = _DISKTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Disk = _reflection.GeneratedProtocolMessageType('Disk', (_message.Message,), {
  'DESCRIPTOR' : _DISK,
  '__module__' : 'disk_pb2'
  # @@protoc_insertion_point(class_scope:imrpc.Disk)
  })
_sym_db.RegisterMessage(Disk)

DiskCreateRequest = _reflection.GeneratedProtocolMessageType('DiskCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISKCREATEREQUEST,
  '__module__' : 'disk_pb2'
  # @@protoc_insertion_point(class_scope:imrpc.DiskCreateRequest)
  })
_sym_db.RegisterMessage(DiskCreateRequest)

DiskGetRequest = _reflection.GeneratedProtocolMessageType('DiskGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISKGETREQUEST,
  '__module__' : 'disk_pb2'
  # @@protoc_insertion_point(class_scope:imrpc.DiskGetRequest)
  })
_sym_db.RegisterMessage(DiskGetRequest)

DiskDeleteRequest = _reflection.GeneratedProtocolMessageType('DiskDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISKDELETEREQUEST,
  '__module__' : 'disk_pb2'
  # @@protoc_insertion_point(class_scope:imrpc.DiskDeleteRequest)
  })
_sym_db.RegisterMessage(DiskDeleteRequest)



_DISKSERVICE = _descriptor.ServiceDescriptor(
  name='DiskService',
  full_name='imrpc.DiskService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=559,
  serialized_end=798,
  methods=[
  _descriptor.MethodDescriptor(
    name='DiskCreate',
    full_name='imrpc.DiskService.DiskCreate',
    index=0,
    containing_service=None,
    input_type=_DISKCREATEREQUEST,
    output_type=_DISK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DiskDelete',
    full_name='imrpc.DiskService.DiskDelete',
    index=1,
    containing_service=None,
    input_type=_DISKDELETEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DiskGet',
    full_name='imrpc.DiskService.DiskGet',
    index=2,
    containing_service=None,
    input_type=_DISKGETREQUEST,
    output_type=_DISK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='VersionGet',
    full_name='imrpc.DiskService.VersionGet',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=imcommon__pb2._VERSIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISKSERVICE)

DESCRIPTOR.services_by_name['DiskService'] = _DISKSERVICE

# @@protoc_insertion_point(module_scope)
